### ISSUE TITLE
Get images for black and white chess pieces and background image

### ISSUE THREAD

**Issue by chatton** [chatton/ChessProject#3]
Images will be needed to display in the GUI.

**Comment by majo-z** [comment]
I have created image folder and added the chess icon sets...they need to be cut to individual pieces(if we want to use them), There is another way though - to use them as unicode symbols...which means independent of language...we can decide later....link below
https://en.wikipedia.org/wiki/Chess_symbols_in_Unicode

**Comment by majo-z** [comment]
I have removes some icons sets, which will not be used and added individual icons
